---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: black-os
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/aurora-dx-asus
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: brew
    brew-analytics: false
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
    install:
      # - micro
      - starship
    # remove:
      # example: removing firefox (in favor of the flatpak)
      # "firefox" is the main package, "firefox-langpacks" is a dependency
      # - firefox
      # - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      install:
        - app.zen_browser.zen
        - com.logseq.Logseq
      remove:
        - org.gnome.eog
    user: # Also add Flathub user repo, but no user packages
      install:
        - ca.desrt.dconf-editor
        - com.boxy_svg.BoxySVG
        - com.dec05eba.gpu_screen_recorder
        - com.felipekinoshita.Wildcard
        - com.github.Matoking.protontricks
        - com.github.flxzt.rnote
        - com.github.libresprite.LibreSprite
        - com.github.marhkb.Pods
        - com.github.tchx84.Flatseal
        - com.github.wwmm.easyeffects
        - com.github.xournalpp.xournalpp
        - com.obsproject.Studio.Plugin.GStreamerVaapi
        - com.obsproject.Studio.Plugin.Gstreamer
        - com.obsproject.Studio.Plugin.OBSVkCapture
        - com.rafaelmardojai.Blanket
        - com.ranfdev.DistroShelf
        - com.spotify.Client
        - com.usebottles.bottles
        - de.leopoldluley.Clapgrep
        - dev.bragefuglseth.Keypunch
        - dev.vencord.Vesktop
        - io.github.fastrizwaan.WineZGUI
        - io.github.flattool.Warehouse
        - io.github.nokse22.asciidraw
        - io.github.shiftey.Desktop
        - io.httpie.Httpie
        - io.podman_desktop.PodmanDesktop
        - it.mijorus.gearlever
        - md.obsidian.Obsidian
        - me.iepure.devtoolbox
        - net.hovancik.Stretchly
        - net.mkiol.SpeechNote
        - net.mkiol.SpeechNote.Addon.amd
        - net.opentabletdriver.OpenTabletDriver
        - net.sourceforge.Klavaro
        - org.dbgate.DbGate
        - org.fkoehler.KTailctl
        - org.geogebra.GeoGebra
        - org.gimp.GIMP
        - org.gnome.meld
        - org.kde.filelight
        - org.kde.gwenview
        - org.kde.haruna
        - org.kde.kcalc
        - org.kde.kdenlive
        - org.kde.krita
        - org.kde.okular
        - org.kde.yakuake
        - org.kicad.KiCad
        - org.octave.Octave
        - org.rncbc.qpwgraph
        - org.signal.Signal
        - org.winehq.Wine.DLLs.dxvk
        - org.winehq.Wine.gecko
        - org.winehq.Wine.mono
        - org.zotero.Zotero
        - rest.insomnia.Insomnia

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

